language: rust
script:
  - cargo build --verbose
  - cargo test --verbose -- --nocapture
  - cargo doc
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.travis/update_docs.sh