[package]

name = "valico"
version = "0.1.4"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "Rust JSON validator and coercer"
keywords = ["json", "validator"]
license = "MIT"

[dependencies]
regex = "*"
rustc-serialize = "*"

[[test]]
name = "tests"