[package]

name = "valico"
version = "0.7.4"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "JSON Schema validator and JSON coercer"
keywords = ["json", "validator", "json-schema"]
license = "MIT"
documentation = "http://rustless.org/valico/doc/valico/"
homepage = "https://github.com/rustless/valico"

[dependencies]
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
url = "*"
mopa = "*"
jsonway = "*"
uuid = "*"
phf = "*"
phf_macros = "*"

[[test]]
name = "tests"
