[package]

name = "valico"
version = "0.8.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
description = "JSON Schema validator and JSON coercer"
keywords = ["json", "validator", "json-schema"]
license = "MIT"
documentation = "http://rustless.org/valico/doc/valico/"
homepage = "https://github.com/rustless/valico"
build = "build.rs"

[dependencies]
regex = "*"
lazy_static = "0.1.10"
rustc-serialize = "*"
url = "*"
jsonway = "*"
uuid = "*"
phf = "*"
typeable = "*"
traitobject = "*"

[build-dependencies.phf_codegen]
version = "*"

[[test]]
name = "tests"
